// <auto-generated />
using ClothingECommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothingECommerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250424142212_UpdateCustomerSeedData")]
    partial class UpdateCustomerSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingECommerce.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Man"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Women"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Kid"
                        });
                });

            modelBuilder.Entity("ClothingECommerce.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers", t =>
                        {
                            t.HasCheckConstraint("CK_Customer_Password_Length", "LEN(Password) >= 6");

                            t.HasCheckConstraint("CK_Customer_PhoneNo_Length", "LEN(PhoneNo) = 11");
                        });

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "omarsherifelghamry@gmail.com",
                            Name = "omar sherif",
                            Password = "Omar__2004",
                            PhoneNo = "01030222769"
                        },
                        new
                        {
                            ID = 2,
                            Email = "janaSameh@gamil.com",
                            Name = "Jana Sameh",
                            Password = "jana_Sameh_2",
                            PhoneNo = "01005033314"
                        });
                });

            modelBuilder.Entity("ClothingECommerce.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Description = "Effortlessly stylish Boxy Fit Crew Neck Printed Sweatshirt, crafted for ultimate comfort with a bold, vibrant print and relaxed silhouette.",
                            Image = "./photos/man/Boxy Fit Crew Neck Printed Sweatshirt 1199 EGP.avif",
                            Name = "Boxy Fit Crew Neck Printed Sweatshirt",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Description = "Iconic Boxy Fit Crew Neck Printed Sweatshirt, blending cozy softness with a striking graphic design for a standout casual look.",
                            Image = "./photos/man/Boxy Fit Crew Neck Printed Sweatshirt 1199 EGP2.avif",
                            Name = "Boxy Fit Crew Neck Printed Sweatshirt",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 1,
                            Description = "Trendsetting Boxy Fit Crew Neck Printed Sweatshirt, offering plush comfort and a dynamic print for an effortlessly cool vibe.",
                            Image = "./photos/man/Boxy Fit Crew Neck Printed Sweatshirt 1199 EGP3.avif",
                            Name = "Boxy Fit Crew Neck Printed Sweatshirt",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 1,
                            Description = "Timeless Plain T-Shirt with Label, featuring a sleek minimalist design and ultra-soft fabric for versatile, everyday wear.",
                            Image = "./photos/man/Boxy Fit Crew Neck Printed Sweatshirt 1199 EGP4.avif",
                            Name = "PLAIN T-SHIRT WITH LABEL",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 1,
                            Description = "Sophisticated Regular Fit Long Sleeve Shirt, tailored for a polished look with breathable, lightweight fabric for all-day comfort.",
                            Image = "./photos/man/Regular Fit Long Sleeve Shirt 1499 EGP.avif",
                            Name = "Regular Fit Long Sleeve Shirt",
                            Price = 1499m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 1,
                            Description = "Breezy Relax Fit Apache Neck Cotton Shirt, adorned with intricate embroidery for a laid-back yet refined summer style.",
                            Image = "./photos/man/Relax Fit Apache Neck Cotton Embroidered Short Sleeve Shirt 1299 EGP.avif",
                            Name = "Relax Fit Apache Neck Cotton Shirt",
                            Price = 1299m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 1,
                            Description = "Vibrant Oversize Fit Resort Collar Patterned Shirt, crafted from airy cotton with a bold pattern for a relaxed, tropical flair.",
                            Image = "./photos/man/Oversize Fit Resort Collar Patterned Cotton Shirt 999 EGP.avif",
                            Name = "Oversize Fit Resort Collar Patterned Shirt",
                            Price = 1390m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 1,
                            Description = "Chic Regular Fit Apache Neck Viscose Shirt, featuring sleek stripes and silky-smooth fabric for a refined, casual elegance.",
                            Image = "./photos/man/Regular Fit Apache Neck Viscose Striped Short Sleeve Shirt 999 EGP.avif",
                            Name = "Regular Fit Apache Neck Viscose Shirt",
                            Price = 999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 1,
                            Description = "Sleek Modern Fit Blazer, expertly tailored for a sharp, contemporary silhouette with premium fabric for lasting sophistication.",
                            Image = "./photos/man/Modern Fit Blazer 2999 EGP.avif",
                            Name = "Modern Fit Blazer",
                            Price = 2999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 1,
                            Description = "Luxurious Relax Fit Lined Blazer, combining a laid-back cut with refined lining for unparalleled comfort and style.",
                            Image = "./photos/man/Relax Fit Lined Blazer 3599 EGP.avif",
                            Name = "Relax Fit Lined Blazer",
                            Price = 3599m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 11,
                            CategoryID = 1,
                            Description = "Stylish Modern Fit Lined Blazer Jacket, offering a tailored fit with premium lining for a polished and comfortable look.",
                            Image = "./photos/man/Modern Fit Lined Blazer Jacket 2499 EGP.avif",
                            Name = "Modern Fit Lined Blazer Jacket",
                            Price = 2499m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 12,
                            CategoryID = 1,
                            Description = "Elegant Regular Fit Lined Blazer, designed for a classic silhouette with high-quality lining for all-day comfort.",
                            Image = "./photos/man/Regular Fit Lined Blazer 3999 EGP.avif",
                            Name = "Regular Fit Lined Blazer",
                            Price = 3999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 13,
                            CategoryID = 1,
                            Description = "Dynamic NBA Golden State Warriors Sports Shorts, crafted for comfort and style, perfect for fans and active wear.",
                            Image = "./photos/man/DeFactoFit NBA Golden State Warriors Standard Fit Sports Shorts 799 EGP.avif",
                            Name = "NBA Golden State Warriors Sports Shorts",
                            Price = 799m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 14,
                            CategoryID = 1,
                            Description = "Versatile Standard Fit Sports Shorts, designed for performance and comfort during active pursuits.",
                            Image = "./photos/man/DeFactoFit Standard Fit Sports Shorts 1299 EGP.avif",
                            Name = "Standard Fit Sports Shorts",
                            Price = 1299m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 15,
                            CategoryID = 1,
                            Description = "Comfortable Standard Fit Sports Woven Shorts, ideal for sports and casual wear with a lightweight, breathable design.",
                            Image = "./photos/man/DeFactoFit Standard Fit Sports Woven Shorts 999 EGP.avif",
                            Name = "Standard Fit Sports Woven Shorts",
                            Price = 999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 16,
                            CategoryID = 1,
                            Description = "Sleek Standard Fit Woven Shorts, offering a relaxed fit and durable fabric for everyday casual wear.",
                            Image = "./photos/man/DeFactoFit Standard Fit Woven Shorts 999 EGP.avif",
                            Name = "Standard Fit Woven Shorts",
                            Price = 999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 17,
                            CategoryID = 3,
                            Description = "Stylish poplin T-shirt with bow appliqué, perfect for a chic and playful kids' look.",
                            Image = "./photos/kids/01037521250-e1.jpg",
                            Name = "POPLIN BOW APPLIQUÉ T",
                            Price = 850m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 18,
                            CategoryID = 3,
                            Description = "Vibrant contrast top for kids, combining bold colors and comfortable fabric for everyday wear.",
                            Image = "./photos/kids/00485516250-e1.jpg",
                            Name = "CONTRAST TOP",
                            Price = 850m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 19,
                            CategoryID = 3,
                            Description = "Trendy denim top with buttons, offering a stylish and durable option for kids' casual outfits.",
                            Image = "./photos/kids/08614640427-e1.jpg",
                            Name = "DENIM TOP WITH BUTTONS",
                            Price = 1390m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 20,
                            CategoryID = 3,
                            Description = "Simple yet stylish plain T-shirt with a label, ideal for kids' versatile and comfortable wear.",
                            Image = "./photos/kids/01716390620-e1.jpg",
                            Name = "PLAIN T-SHIRT WITH LABEL",
                            Price = 390m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 21,
                            CategoryID = 3,
                            Description = "Cozy sweatshirt with embroidered text, perfect for kids to stay warm and fashionable.",
                            Image = "./photos/kids/01880930800-e1.jpg",
                            Name = "EMBROIDERED TEXT SWEATSHIRT",
                            Price = 890m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 22,
                            CategoryID = 3,
                            Description = "Fun bear print sweatshirt, designed to keep kids cozy with a playful and charming design.",
                            Image = "./photos/kids/05643504712-e1.jpg",
                            Name = "BEAR PRINT SWEATSHIRT",
                            Price = 1090m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 23,
                            CategoryID = 3,
                            Description = "Stylish zip-up with embroidered slogan, offering kids a trendy and comfortable outerwear option.",
                            Image = "./photos/kids/05431527098-e1.jpg",
                            Name = "EMBROIDERED SLOGAN WITH ZIP",
                            Price = 1390m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 24,
                            CategoryID = 3,
                            Description = "Charming shirt with floral appliqué, adding a touch of elegance to kids' casual wardrobes.",
                            Image = "./photos/kids/01099808250-e1.jpg",
                            Name = "SHIRT WITH FLORAL APPLIQUÉ",
                            Price = 1390m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 25,
                            CategoryID = 3,
                            Description = "Cool textured striped Bermuda shorts, perfect for kids' active and stylish summer looks.",
                            Image = "./photos/kids/00794505400-e1.jpg",
                            Name = "TEXTURED STRIPED BERMUDA SHORTS",
                            Price = 1190m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 26,
                            CategoryID = 3,
                            Description = "Sleek textured striped shirt, offering kids a polished yet comfortable option for any occasion.",
                            Image = "./photos/kids/00794503400-e1.jpg",
                            Name = "TEXTURED STRIPED SHIRT",
                            Price = 1290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 27,
                            CategoryID = 3,
                            Description = "Lightweight linen Bermuda shorts with a belt, ideal for kids' breezy and stylish summer outfits.",
                            Image = "./photos/kids/01258500052-e1.jpg",
                            Name = "LINEN BERMUDA SHORTS WITH BELT",
                            Price = 1290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 28,
                            CategoryID = 3,
                            Description = "Casual linen patch Bermuda shorts, designed for kids' comfort and trendy summer adventures.",
                            Image = "./photos/kids/02878502712-e1.jpg",
                            Name = "LINEN PATCH BERMUDA SHORTS",
                            Price = 1190m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 29,
                            CategoryID = 3,
                            Description = "Exciting The Lion King © Disney themed clothing, perfect for kids who love iconic characters.",
                            Image = "./photos/kids/20310418999-e1.jpg",
                            Name = "THE LION KING © DISNEY",
                            Price = 1090m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 30,
                            CategoryID = 3,
                            Description = "Playful Lilo & Stitch © Disney themed clothing, bringing fun and comfort to kids' wardrobes.",
                            Image = "./photos/kids/20310373999-e1.jpg",
                            Name = "LILO & STITCH © DISNEY",
                            Price = 650m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 31,
                            CategoryID = 3,
                            Description = "Adorable Minnie Mouse © Disney themed clothing, ideal for kids with a love for classic characters.",
                            Image = "./photos/kids/20310338999-e1.jpg",
                            Name = "MINNIE MOUSE © DISNEY",
                            Price = 1090m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 32,
                            CategoryID = 3,
                            Description = "Magical Mickey Mouse Fantasia © Disney themed clothing, perfect for kids' whimsical and cozy style.",
                            Image = "./photos/kids/00653546800-e1.jpg",
                            Name = "MICKEY MOUSE FANTASIA © DISNEY",
                            Price = 1090m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 33,
                            CategoryID = 2,
                            Description = "Cozy NFL Giants hoodie, perfect for women to show team spirit with a comfortable and stylish fit.",
                            Image = "./photos/women/NFL GIANTS HOODIE  3,290 EGP.jpg",
                            Name = "NFL GIANTS HOODIE",
                            Price = 3290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 34,
                            CategoryID = 2,
                            Description = "Casual hoodie with pockets, offering a relaxed fit and practical style for women.",
                            Image = "./photos/women/HOODIE WITH POCKETS +2  1,690 EGP.jpg",
                            Name = "HOODIE WITH POCKETS +2",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 35,
                            CategoryID = 2,
                            Description = "Cropped fleece Harvard University sweatshirt, combining collegiate pride with trendy women’s fashion.",
                            Image = "./photos/women/HARVARD UNIVERSITY CROPPED FLEECE SWEATSHIRT  2,290 EGP.jpg",
                            Name = "HARVARD UNIVERSITY SWEATSHIRT",
                            Price = 2290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 36,
                            CategoryID = 2,
                            Description = "Stylish NFL Bills hoodie, designed for women to support their team in comfort.",
                            Image = "./photos/women/NFL BILLS HOODIE  2,990 EGP.jpg",
                            Name = "NFL BILLS HOODIE",
                            Price = 2990m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 37,
                            CategoryID = 2,
                            Description = "Trendy high-waist wide-leg TRF jeans, offering a bold and fashionable look for women.",
                            Image = "./photos/women/HIGH-WAIST WIDE-LEG TRF JEANS +3  2,990 EGP .jpg",
                            Name = "HIGH-WAIST WIDE-LEG TRF JEANS +3",
                            Price = 2990m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 38,
                            CategoryID = 2,
                            Description = "Trendy high-waist wide-leg TRF jeans, offering a bold and fashionable look for women.",
                            Image = "./photos/women/HIGH-WAIST WIDE-LEG TRF JEANS +3  2,990 EGP.jpg",
                            Name = "HIGH-WAIST WIDE-LEG TRF JEANS +3",
                            Price = 2990m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 39,
                            CategoryID = 2,
                            Description = "Sophisticated Yale™ polo neck sweatshirt, blending classic style with modern women’s fashion.",
                            Image = "./photos/women/YALE™ POLO NECK SWEATSHIRT  2,490 EGP.jpg",
                            Name = "YALE™ POLO NECK SWEATSHIRT",
                            Price = 2490m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 40,
                            CategoryID = 2,
                            Description = "Chic wide-leg mid-rise darted jeans, perfect for a stylish and comfortable women’s outfit.",
                            Image = "./photos/women/Z1975 WIDE-LEG MID-RISE DARTED JEANS  2,490 EGP.jpg",
                            Name = "WIDE-LEG MID-RISE DARTED JEANS",
                            Price = 2490m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 41,
                            CategoryID = 2,
                            Description = "Alluring Dark Romance EDP 80ml, a captivating fragrance for women.",
                            Image = "./photos/women/DARK ROMANCE EDP 80 ML : 2.71 oz  1,690 EGP.jpg",
                            Name = "DARK ROMANCE EDP 80 ML : 2.71 oz",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 42,
                            CategoryID = 2,
                            Description = "Enchanting Immortal Vanilla EDP 80ml, a sweet and lasting scent for women.",
                            Image = "./photos/women/IMMORTAL VANILLA EDP 80 ML : 2.71 oz  1,690 EGP.jpg",
                            Name = "IMMORTAL VANILLA EDP 80 ML : 2.71 oz",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 43,
                            CategoryID = 2,
                            Description = "Mesmerizing Hypnotic Vanilla Bloom EDP 80ml, a floral-vanilla fragrance for women.",
                            Image = "./photos/women/HYPNOTIC VANILLA BLOOM EDP 80ML : 2.71 oz  1,690 EGP.jpg",
                            Name = "HYPNOTIC VANILLA BLOOM EDP 80ML : 2.71 oz",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 44,
                            CategoryID = 2,
                            Description = "Bold Red Zara Temptation EDP 80ml, a vibrant and tempting scent for women.",
                            Image = "./photos/women/RED ZARA TEMPTATION EDP 80ML : 2.71 oz  1,690 EGP.jpg",
                            Name = "RED ZARA TEMPTATION EDP 80ML : 2.71 oz",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 45,
                            CategoryID = 2,
                            Description = "Cozy turn-up knit beanie, a stylish and warm accessory for women.",
                            Image = "./photos/women/TURN-UP KNIT BEANIE  1,090 EGP.jpg",
                            Name = "TURN-UP KNIT BEANIE",
                            Price = 1090m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 46,
                            CategoryID = 2,
                            Description = "Elegant flower hair clip, adding a feminine touch to women’s hairstyles.",
                            Image = "./photos/women/FLOWER HAIR CLIP  1,290 EGP.jpg",
                            Name = "FLOWER HAIR CLIP",
                            Price = 1290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 47,
                            CategoryID = 2,
                            Description = "Striking maxi enamelled flower earrings, a bold accessory for women.",
                            Image = "./photos/women/MAXI ENAMELLED FLOWER EARRINGS  1,290 EGP.jpg",
                            Name = "MAXI ENAMELLED FLOWER EARRINGS",
                            Price = 1290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 48,
                            CategoryID = 2,
                            Description = "Unique cord sun necklace, a chic and summery accessory for women.",
                            Image = "./photos/women/CORD SUN NECKLACE  1,490 EGP.jpg",
                            Name = "CORD SUN NECKLACE",
                            Price = 1490m,
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("ClothingECommerce.Models.Product", b =>
                {
                    b.HasOne("ClothingECommerce.Models.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClothingECommerce.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
