// <auto-generated />
using ClothingECommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothingECommerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250423184124_UpdateDataBase")]
    partial class UpdateDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingECommerce.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Man"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Women"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Kid"
                        });
                });

            modelBuilder.Entity("ClothingECommerce.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Description = "Effortlessly stylish Boxy Fit Crew Neck Printed Sweatshirt, crafted for ultimate comfort with a bold, vibrant print and relaxed silhouette.",
                            Image = "../photos/man/Boxy_Fit_Crew_Neck_Printed_Sweatshirt_1199_EGP.avif",
                            Name = "Boxy Fit Crew Neck Printed Sweatshirt",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Description = "Iconic Boxy Fit Crew Neck Printed Sweatshirt, blending cozy softness with a striking graphic design for a standout casual look.",
                            Image = "../photos/man/Boxy_Fit_Crew_Neck_Printed_Sweatshirt_1199_EGP2.avif",
                            Name = "Boxy Fit Crew Neck Printed Sweatshirt",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 1,
                            Description = "Trendsetting Boxy Fit Crew Neck Printed Sweatshirt, offering plush comfort and a dynamic print for an effortlessly cool vibe.",
                            Image = "../photos/man/Boxy_Fit_Crew_Neck_Printed_Sweatshirt_1199_EGP3.avif",
                            Name = "Boxy Fit Crew Neck Printed Sweatshirt",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 1,
                            Description = "Timeless Plain T-Shirt with Label, featuring a sleek minimalist design and ultra-soft fabric for versatile, everyday wear.",
                            Image = "../photos/man/PLAIN_T_SHIRT_WITH_LABEL_1199_EGP.avif",
                            Name = "Plain T-Shirt with Label",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 1,
                            Description = "Sophisticated Regular Fit Long Sleeve Shirt, tailored for a polished look with breathable, lightweight fabric for all-day comfort.",
                            Image = "../photos/man/Regular_Fit_Long_Sleeve_Shirt_1499_EGP.avif",
                            Name = "Regular Fit Long Sleeve Shirt",
                            Price = 1499m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 1,
                            Description = "Breezy Relax Fit Apache Neck Cotton Shirt, adorned with intricate embroidery for a laid-back yet refined summer style.",
                            Image = "../photos/man/Relax_Fit_Apache_Neck_Cotton_Embroidered_Short_Sleeve_Shirt_1299_EGP.avif",
                            Name = "Relax Fit Apache Neck Cotton Shirt",
                            Price = 1299m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 1,
                            Description = "Vibrant Oversize Fit Resort Collar Patterned Shirt, crafted from airy cotton with a bold pattern for a relaxed, tropical flair.",
                            Image = "../photos/man/Oversize_Fit_Resort_Collar_Patterned_Cotton_Shirt_999_EGP.avif",
                            Name = "Oversize Fit Resort Collar Patterned Shirt",
                            Price = 1390m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 1,
                            Description = "Chic Regular Fit Apache Neck Viscose Shirt, featuring sleek stripes and silky-smooth fabric for a refined, casual elegance.",
                            Image = "../photos/man/Regular_Fit_Apache_Neck_Viscose_Striped_Short_Sleeve_Shirt_999_EGP.avif",
                            Name = "Regular Fit Apache Neck Viscose Shirt",
                            Price = 999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 1,
                            Description = "Sleek Modern Fit Blazer, expertly tailored for a sharp, contemporary silhouette with premium fabric for lasting sophistication.",
                            Image = "../photos/man/Modern_Fit_Blazer_2999_EGP.avif",
                            Name = "Modern Fit Blazer",
                            Price = 2999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 1,
                            Description = "Luxurious Relax Fit Lined Blazer, combining a laid-back cut with refined lining for unparalleled comfort and style.",
                            Image = "../photos/man/Relax_Fit_Lined_Blazer_3599_EGP.avif",
                            Name = "Relax Fit Lined Blazer",
                            Price = 3599m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 11,
                            CategoryID = 1,
                            Description = "Dapper Checkered Formal Shirt, featuring a crisp check pattern and tailored fit for a polished, professional appearance.",
                            Image = "../photos/man/Checkered_Formal_Shirt_1799_EGP.avif",
                            Name = "Checkered Formal Shirt",
                            Price = 1799m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 12,
                            CategoryID = 1,
                            Description = "Sharp Slim Fit Blazer, designed for a streamlined silhouette with high-quality fabric for a modern, elegant look.",
                            Image = "../photos/man/Slim_Fit_Blazer_2999_EGP.avif",
                            Name = "Slim Fit Blazer",
                            Price = 2999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 13,
                            CategoryID = 1,
                            Description = "Easygoing Casual Relaxed Fit T-Shirt, crafted from soft, breathable cotton for a comfortable, laid-back everyday style.",
                            Image = "../photos/man/Casual_Relaxed_Fit_T_Shirt_799_EGP.avif",
                            Name = "Casual Relaxed Fit T-Shirt",
                            Price = 799m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 14,
                            CategoryID = 1,
                            Description = "Dynamic Sporty Zip-Up Hoodie, blending cozy warmth with a sleek design for active lifestyles and casual outings.",
                            Image = "../photos/man/Sporty_Zip_Up_Hoodie_1399_EGP.avif",
                            Name = "Sporty Zip-Up Hoodie",
                            Price = 1399m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 15,
                            CategoryID = 1,
                            Description = "Essential Classic Crew Neck T-Shirt, offering timeless simplicity and ultra-soft comfort for versatile, everyday wear.",
                            Image = "../photos/man/Classic_Crew_Neck_T_Shirt_699_EGP.avif",
                            Name = "Classic Crew Neck T-Shirt",
                            Price = 699m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 16,
                            CategoryID = 1,
                            Description = "Comfort-driven Soft Cotton Casual Shirt, featuring a relaxed fit and buttery-soft fabric for effortless, all-day style.",
                            Image = "../photos/man/Soft_Cotton_Casual_Shirt_1299_EGP.avif",
                            Name = "Soft Cotton Casual Shirt",
                            Price = 1299m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 17,
                            CategoryID = 3,
                            Description = "Stylish poplin T-shirt with bow appliqué, perfect for a chic and playful kids' look.",
                            Image = "../photos/kids/01037521250-e1.jpg",
                            Name = "POPLIN BOW APPLIQUÉ T",
                            Price = 850m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 18,
                            CategoryID = 3,
                            Description = "Trendy contrast top for kids, combining comfort and bold style.",
                            Image = "../photos/kids/00485516250-e1.jpg",
                            Name = "CONTRAST TOP",
                            Price = 850m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 19,
                            CategoryID = 3,
                            Description = "Cool denim top with button details, ideal for a casual yet stylish outfit.",
                            Image = "../photos/kids/08614640427-e1.jpg",
                            Name = "DENIM TOP WITH BUTTONS",
                            Price = 1390m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 20,
                            CategoryID = 3,
                            Description = "Simple yet trendy plain T-shirt with a subtle label detail for everyday wear.",
                            Image = "../photos/kids/01716390620-e1.jpg",
                            Name = "PLAIN T-SHIRT WITH LABEL",
                            Price = 390m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 21,
                            CategoryID = 3,
                            Description = "Cozy sweatshirt with embroidered text, adding a fun touch to kids' wardrobes.",
                            Image = "../photos/kids/01880930800-e1.jpg",
                            Name = "EMBROIDERED TEXT SWEATSHIRT",
                            Price = 890m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 22,
                            CategoryID = 3,
                            Description = "Adorable bear print sweatshirt, perfect for a cute and comfy look.",
                            Image = "../photos/kids/05643504712-e1.jpg",
                            Name = "BEAR PRINT SWEATSHIRT",
                            Price = 1090m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 23,
                            CategoryID = 3,
                            Description = "Stylish zip-up with embroidered slogan, blending comfort and attitude.",
                            Image = "../photos/kids/05431527098-e1.jpg",
                            Name = "EMBROIDERED SLOGAN WITH ZIP",
                            Price = 1390m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 24,
                            CategoryID = 3,
                            Description = "Charming shirt with floral appliqué, adding a touch of elegance to kids' fashion.",
                            Image = "../photos/kids/01099808250-e1.jpg",
                            Name = "SHIRT WITH FLORAL APPLIQUÉ",
                            Price = 1390m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 25,
                            CategoryID = 3,
                            Description = "Textured striped Bermuda shorts, offering a cool and casual vibe.",
                            Image = "../photos/kids/00794505400-e1.jpg",
                            Name = "TEXTURED STRIPED BERMUDA SHORTS",
                            Price = 1190m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 26,
                            CategoryID = 3,
                            Description = "Textured striped shirt, perfect for a polished yet relaxed kids' outfit.",
                            Image = "../photos/kids/00794503400-e1.jpg",
                            Name = "TEXTURED STRIPED SHIRT",
                            Price = 1290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 27,
                            CategoryID = 3,
                            Description = "Linen Bermuda shorts with a belt, combining comfort and a smart look.",
                            Image = "../photos/kids/01258500052-e1.jpg",
                            Name = "LINEN BERMUDA SHORTS WITH BELT",
                            Price = 1290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 28,
                            CategoryID = 3,
                            Description = "Linen Bermuda shorts with patch details, ideal for a stylish summer outfit.",
                            Image = "../photos/kids/02878502712-e1.jpg",
                            Name = "LINEN PATCH BERMUDA SHORTS",
                            Price = 1190m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 29,
                            CategoryID = 3,
                            Description = "Fun The Lion King © Disney themed apparel, perfect for young fans.",
                            Image = "../photos/kids/20310418999-e1.jpg",
                            Name = "THE LION KING © DISNEY",
                            Price = 1090m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 30,
                            CategoryID = 3,
                            Description = "Playful Lilo & Stitch © Disney apparel, bringing fun to kids' wardrobes.",
                            Image = "../photos/kids/20310373999-e1.jpg",
                            Name = "LILO & STITCH © DISNEY",
                            Price = 650m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 31,
                            CategoryID = 3,
                            Description = "Charming Minnie Mouse © Disney apparel, a delightful addition for kids.",
                            Image = "../photos/kids/20310338999-e1.jpg",
                            Name = "MINNIE MOUSE © DISNEY",
                            Price = 1090m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 32,
                            CategoryID = 3,
                            Description = "Magical Mickey Mouse Fantasia © Disney apparel, perfect for Disney lovers.",
                            Image = "../photos/kids/00653546800-e1.jpg",
                            Name = "MICKEY MOUSE FANTASIA © DISNEY",
                            Price = 1090m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 33,
                            CategoryID = 2,
                            Description = "Cozy NFL Giants hoodie, perfect for showing team spirit in style.",
                            Image = "../photos/women/NFL GIANTS HOODIE  3,290 EGP.jpg",
                            Name = "NFL GIANTS HOODIE",
                            Price = 3290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 34,
                            CategoryID = 2,
                            Description = "Comfortable hoodie with pockets, ideal for a casual and practical look.",
                            Image = "../photos/women/HOODIE WITH POCKETS +2  1,690 EGP.jpg",
                            Name = "HOODIE WITH POCKETS +2",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 35,
                            CategoryID = 2,
                            Description = "Stylish Harvard University cropped fleece sweatshirt, blending comfort and collegiate pride.",
                            Image = "../photos/women/HARVARD UNIVERSITY CROPPED FLEECE SWEATSHIRT  2,290 EGP.jpg",
                            Name = "HARVARD UNIVERSITY SWEATSHIRT",
                            Price = 2290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 36,
                            CategoryID = 2,
                            Description = "Bold NFL Bills hoodie, designed for fans with a passion for comfort and team loyalty.",
                            Image = "../photos/women/NFL BILLS HOODIE  2,990 EGP.jpg",
                            Name = "NFL BILLS HOODIE",
                            Price = 2990m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 37,
                            CategoryID = 2,
                            Description = "Trendy high-waist wide-leg TRF jeans, offering a chic and relaxed silhouette.",
                            Image = "../photos/women/HIGH-WAIST WIDE-LEG TRF JEANS +3  2,990 EGP.jpg",
                            Name = "HIGH-WAIST WIDE-LEG TRF JEANS +3",
                            Price = 2990m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 38,
                            CategoryID = 2,
                            Description = "Elegant Yale™ polo neck sweatshirt, combining sophistication with cozy comfort.",
                            Image = "../photos/women/YALE™ POLO NECK SWEATSHIRT  2,490 EGP.jpg",
                            Name = "YALE™ POLO NECK SWEATSHIRT",
                            Price = 2490m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 39,
                            CategoryID = 2,
                            Description = "Fashion-forward wide-leg mid-rise darted jeans, perfect for a modern and stylish look.",
                            Image = "../photos/women/Z1975 WIDE-LEG MID-RISE DARTED JEANS  2,490 EGP.jpg",
                            Name = "WIDE-LEG MID-RISE DARTED JEANS",
                            Price = 2490m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 40,
                            CategoryID = 2,
                            Description = "Captivating Dark Romance EDP, a bold and alluring fragrance for women.",
                            Image = "../photos/women/DARK ROMANCE EDP 80 ML : 2.71 oz  1,690 EGP.jpg",
                            Name = "DARK ROMANCE EDP 80 ML : 2.71 oz",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 41,
                            CategoryID = 2,
                            Description = "Enchanting Immortal Vanilla EDP, offering a sweet and timeless scent.",
                            Image = "../photos/women/IMMORTAL VANILLA EDP 80 ML : 2.71 oz  1,690 EGP.jpg",
                            Name = "IMMORTAL VANILLA EDP 80 ML : 2.71 oz",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 42,
                            CategoryID = 2,
                            Description = "Mesmerizing Hypnotic Vanilla Bloom EDP, a floral and vanilla-infused fragrance.",
                            Image = "../photos/women/HYPNOTIC VANILLA BLOOM EDP 80ML : 2.71 oz  1,690 EGP.jpg",
                            Name = "HYPNOTIC VANILLA BLOOM EDP 80ML : 2.71 oz",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 43,
                            CategoryID = 2,
                            Description = "Seductive Red Zara Temptation EDP, a vibrant and irresistible fragrance.",
                            Image = "../photos/women/RED ZARA TEMPTATION EDP 80ML : 2.71 oz  1,690 EGP.jpg",
                            Name = "RED ZARA TEMPTATION EDP 80ML : 2.71 oz",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 44,
                            CategoryID = 2,
                            Description = "Cozy turn-up knit beanie, perfect for adding warmth and style to any outfit.",
                            Image = "../photos/women/TURN-UP KNIT BEANIE  1,090 EGP.jpg",
                            Name = "TURN-UP KNIT BEANIE",
                            Price = 1090m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 45,
                            CategoryID = 2,
                            Description = "Elegant flower hair clip, adding a delicate and feminine touch to hairstyles.",
                            Image = "../photos/women/FLOWER HAIR CLIP  1,290 EGP.jpg",
                            Name = "FLOWER HAIR CLIP",
                            Price = 1290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 46,
                            CategoryID = 2,
                            Description = "Striking maxi enamelled flower earrings, perfect for a bold and floral statement.",
                            Image = "../photos/women/MAXI ENAMELLED FLOWER EARRINGS  1,290 EGP.jpg",
                            Name = "MAXI ENAMELLED FLOWER EARRINGS",
                            Price = 1290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 47,
                            CategoryID = 2,
                            Description = "Unique cord sun necklace, blending bohemian charm with a radiant design.",
                            Image = "../photos/women/CORD SUN NECKLACE  1,490 EGP.jpg",
                            Name = "CORD SUN NECKLACE",
                            Price = 1490m,
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("ClothingECommerce.Models.Product", b =>
                {
                    b.HasOne("ClothingECommerce.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ClothingECommerce.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
