// <auto-generated />
using ClothingECommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothingECommerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250423202122_fixLink")]
    partial class fixLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingECommerce.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Man"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Women"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Kid"
                        });
                });

            modelBuilder.Entity("ClothingECommerce.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Description = "Effortlessly stylish Boxy Fit Crew Neck Printed Sweatshirt, crafted for ultimate comfort with a bold, vibrant print and relaxed silhouette.",
                            Image = "/Users/compumagic/Downloads/frontend-project/photos/man/Boxy Fit Crew Neck Printed Sweatshirt 1199 EGP.avif",
                            Name = "Boxy Fit Crew Neck Printed Sweatshirt",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Description = "Iconic Boxy Fit Crew Neck Printed Sweatshirt, blending cozy softness with a striking graphic design for a standout casual look.",
                            Image = "./photos/man/Boxy Fit Crew Neck Printed Sweatshirt 1199 EGP2.avif",
                            Name = "Boxy Fit Crew Neck Printed Sweatshirt",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 1,
                            Description = "Trendsetting Boxy Fit Crew Neck Printed Sweatshirt, offering plush comfort and a dynamic print for an effortlessly cool vibe.",
                            Image = "./photos/man/Boxy Fit Crew Neck Printed Sweatshirt 1199 EGP3.avif",
                            Name = "Boxy Fit Crew Neck Printed Sweatshirt",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 1,
                            Description = "Timeless Plain T-Shirt with Label, featuring a sleek minimalist design and ultra-soft fabric for versatile, everyday wear.",
                            Image = "./photos/man/Plain T Shirt With Label 1199 EGP.avif",
                            Name = "Plain T-Shirt with Label",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 1,
                            Description = "Sophisticated Regular Fit Long Sleeve Shirt, tailored for a polished look with breathable, lightweight fabric for all-day comfort.",
                            Image = "./photos/man/Regular Fit Long Sleeve Shirt 1499 EGP.avif",
                            Name = "Regular Fit Long Sleeve Shirt",
                            Price = 1499m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 1,
                            Description = "Breezy Relax Fit Apache Neck Cotton Shirt, adorned with intricate embroidery for a laid-back yet refined summer style.",
                            Image = "./photos/man/Relax Fit Apache Neck Cotton Embroidered Short Sleeve Shirt 1299 EGP.avif",
                            Name = "Relax Fit Apache Neck Cotton Shirt",
                            Price = 1299m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 1,
                            Description = "Vibrant Oversize Fit Resort Collar Patterned Shirt, crafted from airy cotton with a bold pattern for a relaxed, tropical flair.",
                            Image = "./photos/man/Oversize Fit Resort Collar Patterned Cotton Shirt 999 EGP.avif",
                            Name = "Oversize Fit Resort Collar Patterned Shirt",
                            Price = 1390m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 1,
                            Description = "Chic Regular Fit Apache Neck Viscose Shirt, featuring sleek stripes and silky-smooth fabric for a refined, casual elegance.",
                            Image = "./photos/man/Regular Fit Apache Neck Viscose Striped Short Sleeve Shirt 999 EGP.avif",
                            Name = "Regular Fit Apache Neck Viscose Shirt",
                            Price = 999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 1,
                            Description = "Sleek Modern Fit Blazer, expertly tailored for a sharp, contemporary silhouette with premium fabric for lasting sophistication.",
                            Image = "./photos/man/Modern Fit Blazer 2999 EGP.avif",
                            Name = "Modern Fit Blazer",
                            Price = 2999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 1,
                            Description = "Luxurious Relax Fit Lined Blazer, combining a laid-back cut with refined lining for unparalleled comfort and style.",
                            Image = "./photos/man/Relax Fit Lined Blazer 3599 EGP.avif",
                            Name = "Relax Fit Lined Blazer",
                            Price = 3599m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 11,
                            CategoryID = 1,
                            Description = "Dapper Checkered Formal Shirt, featuring a crisp check pattern and tailored fit for a polished, professional appearance.",
                            Image = "./photos/man/Checkered Formal Shirt 1799 EGP.avif",
                            Name = "Checkered Formal Shirt",
                            Price = 1799m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 12,
                            CategoryID = 1,
                            Description = "Sharp Slim Fit Blazer, designed for a streamlined silhouette with high-quality fabric for a modern, elegant look.",
                            Image = "./photos/man/Slim Fit Blazer 2999 EGP.avif",
                            Name = "Slim Fit Blazer",
                            Price = 2999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 13,
                            CategoryID = 1,
                            Description = "Easygoing Casual Relaxed Fit T-Shirt, crafted from soft, breathable cotton for a comfortable, laid-back everyday style.",
                            Image = "./photos/man/Casual Relaxed Fit T Shirt 799 EGP.avif",
                            Name = "Casual Relaxed Fit T-Shirt",
                            Price = 799m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 14,
                            CategoryID = 1,
                            Description = "Dynamic Sporty Zip-Up Hoodie, blending cozy warmth with a sleek design for active lifestyles and casual outings.",
                            Image = "./photos/man/Sporty Zip Up Hoodie 1399 EGP.avif",
                            Name = "Sporty Zip-Up Hoodie",
                            Price = 1399m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 15,
                            CategoryID = 1,
                            Description = "Essential Classic Crew Neck T-Shirt, offering timeless simplicity and ultra-soft comfort for versatile, everyday wear.",
                            Image = "./photos/man/Classic Crew Neck T Shirt 699 EGP.avif",
                            Name = "Classic Crew Neck T-Shirt",
                            Price = 699m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 16,
                            CategoryID = 1,
                            Description = "Comfort-driven Soft Cotton Casual Shirt, featuring a relaxed fit and buttery-soft fabric for effortless, all-day style.",
                            Image = "./photos/man/Soft Cotton Casual Shirt 1299 EGP.avif",
                            Name = "Soft Cotton Casual Shirt",
                            Price = 1299m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 17,
                            CategoryID = 3,
                            Description = "Stylish poplin T-shirt with bow appliqué, perfect for a chic and playful kids' look.",
                            Image = "./photos/kids/01037521250-e1.jpg",
                            Name = "POPLIN BOW APPLIQUÉ T",
                            Price = 850m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 33,
                            CategoryID = 2,
                            Description = "Cozy NFL Giants hoodie, perfect for showing team spirit in style.",
                            Image = "./photos/women/NFL Giants Hoodie 3290 EGP.jpg",
                            Name = "NFL GIANTS HOODIE",
                            Price = 3290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 34,
                            CategoryID = 2,
                            Description = "Comfortable hoodie with pockets, ideal for a casual and practical look.",
                            Image = "./photos/women/Hoodie With Pockets +2 1690 EGP.jpg",
                            Name = "HOODIE WITH POCKETS +2",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 35,
                            CategoryID = 2,
                            Description = "Stylish Harvard University cropped fleece sweatshirt, blending comfort and collegiate pride.",
                            Image = "./photos/women/Harvard University Cropped Fleece Sweatshirt 2290 EGP.jpg",
                            Name = "HARVARD UNIVERSITY SWEATSHIRT",
                            Price = 2290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 36,
                            CategoryID = 2,
                            Description = "Bold NFL Bills hoodie, designed for fans with a passion for comfort and team loyalty.",
                            Image = "./photos/women/NFL Bills Hoodie 2990 EGP.jpg",
                            Name = "NFL BILLS HOODIE",
                            Price = 2990m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 37,
                            CategoryID = 2,
                            Description = "Trendy high-waist wide-leg TRF jeans, offering a chic and relaxed silhouette.",
                            Image = "./photos/women/High Waist Wide Leg TRF Jeans +3 2990 EGP.jpg",
                            Name = "HIGH-WAIST WIDE-LEG TRF JEANS +3",
                            Price = 2990m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 38,
                            CategoryID = 2,
                            Description = "Elegant Yale™ polo neck sweatshirt, combining sophistication with cozy comfort.",
                            Image = "./photos/women/Yale Polo Neck Sweatshirt 2490 EGP.jpg",
                            Name = "YALE™ POLO NECK SWEATSHIRT",
                            Price = 2490m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 39,
                            CategoryID = 2,
                            Description = "Fashion-forward wide-leg mid-rise darted jeans, perfect for a modern and stylish look.",
                            Image = "./photos/women/Z1975 Wide Leg Mid Rise Darted Jeans 2490 EGP.jpg",
                            Name = "WIDE-LEG MID-RISE DARTED JEANS",
                            Price = 2490m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 40,
                            CategoryID = 2,
                            Description = "Captivating Dark Romance EDP, a bold and alluring fragrance for women.",
                            Image = "./photos/women/Dark Romance EDP 80 ML 2.71 oz 1690 EGP.jpg",
                            Name = "DARK ROMANCE EDP 80 ML : 2.71 oz",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 41,
                            CategoryID = 2,
                            Description = "Enchanting Immortal Vanilla EDP, offering a sweet and timeless scent.",
                            Image = "./photos/women/Immortal Vanilla EDP 80 ML 2.71 oz 1690 EGP.jpg",
                            Name = "IMMORTAL VANILLA EDP 80 ML : 2.71 oz",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 42,
                            CategoryID = 2,
                            Description = "Mesmerizing Hypnotic Vanilla Bloom EDP, a floral and vanilla-infused fragrance.",
                            Image = "./photos/women/Hypnotic Vanilla Bloom EDP 80ML 2.71 oz 1690 EGP.jpg",
                            Name = "HYPNOTIC VANILLA BLOOM EDP 80ML : 2.71 oz",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 43,
                            CategoryID = 2,
                            Description = "Seductive Red Zara Temptation EDP, a vibrant and irresistible fragrance.",
                            Image = "./photos/women/Red Zara Temptation EDP 80ML 2.71 oz 1690 EGP.jpg",
                            Name = "RED ZARA TEMPTATION EDP 80ML : 2.71 oz",
                            Price = 1690m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 44,
                            CategoryID = 2,
                            Description = "Cozy turn-up knit beanie, perfect for adding warmth and style to any outfit.",
                            Image = "./photos/women/Turn Up Knit Beanie 1090 EGP.jpg",
                            Name = "TURN-UP KNIT BEANIE",
                            Price = 1090m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 45,
                            CategoryID = 2,
                            Description = "Elegant flower hair clip, adding a delicate and feminine touch to hairstyles.",
                            Image = "./photos/women/Flower Hair Clip 1290 EGP.jpg",
                            Name = "FLOWER HAIR CLIP",
                            Price = 1290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 46,
                            CategoryID = 2,
                            Description = "Striking maxi enamelled flower earrings, perfect for a bold and floral statement.",
                            Image = "./photos/women/Maxi Enamelled Flower Earrings 1290 EGP.jpg",
                            Name = "MAXI ENAMELLED FLOWER EARRINGS",
                            Price = 1290m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 47,
                            CategoryID = 2,
                            Description = "Unique cord sun necklace, blending bohemian charm with a radiant design.",
                            Image = "./photos/women/Cord Sun Necklace 1490 EGP.jpg",
                            Name = "CORD SUN NECKLACE",
                            Price = 1490m,
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("ClothingECommerce.Models.Product", b =>
                {
                    b.HasOne("ClothingECommerce.Models.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClothingECommerce.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
