// <auto-generated />
using ClothingECommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothingECommerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250422000218_NewMigrationName")]
    partial class NewMigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingECommerce.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Man"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Women"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Kid"
                        });
                });

            modelBuilder.Entity("ClothingECommerce.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Description = "Effortlessly stylish Boxy Fit Crew Neck Printed Sweatshirt, crafted for ultimate comfort with a bold, vibrant print and relaxed silhouette.",
                            Image = "../photos/man/Boxy_Fit_Crew_Neck_Printed_Sweatshirt_1199_EGP.avif",
                            Name = "Boxy Fit Crew Neck Printed Sweatshirt",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Description = "Iconic Boxy Fit Crew Neck Printed Sweatshirt, blending cozy softness with a striking graphic design for a standout casual look.",
                            Image = "../photos/man/Boxy_Fit_Crew_Neck_Printed_Sweatshirt_1199_EGP2.avif",
                            Name = "Boxy Fit Crew Neck Printed Sweatshirt",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 1,
                            Description = "Trendsetting Boxy Fit Crew Neck Printed Sweatshirt, offering plush comfort and a dynamic print for an effortlessly cool vibe.",
                            Image = "../photos/man/Boxy_Fit_Crew_Neck_Printed_Sweatshirt_1199_EGP3.avif",
                            Name = "Boxy Fit Crew Neck Printed Sweatshirt",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 1,
                            Description = "Timeless Plain T-Shirt with Label, featuring a sleek minimalist design and ultra-soft fabric for versatile, everyday wear.",
                            Image = "../photos/man/PLAIN_T_SHIRT_WITH_LABEL_1199_EGP.avif",
                            Name = "Plain T-Shirt with Label",
                            Price = 1199m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 1,
                            Description = "Sophisticated Regular Fit Long Sleeve Shirt, tailored for a polished look with breathable, lightweight fabric for all-day comfort.",
                            Image = "../photos/man/Regular_Fit_Long_Sleeve_Shirt_1499_EGP.avif",
                            Name = "Regular Fit Long Sleeve Shirt",
                            Price = 1499m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 1,
                            Description = "Breezy Relax Fit Apache Neck Cotton Shirt, adorned with intricate embroidery for a laid-back yet refined summer style.",
                            Image = "../photos/man/Relax_Fit_Apache_Neck_Cotton_Embroidered_Short_Sleeve_Shirt_1299_EGP.avif",
                            Name = "Relax Fit Apache Neck Cotton Shirt",
                            Price = 1299m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 1,
                            Description = "Vibrant Oversize Fit Resort Collar Patterned Shirt, crafted from airy cotton with a bold pattern for a relaxed, tropical flair.",
                            Image = "../photos/man/Oversize_Fit_Resort_Collar_Patterned_Cotton_Shirt_999_EGP.avif",
                            Name = "Oversize Fit Resort Collar Patterned Shirt",
                            Price = 1390m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 1,
                            Description = "Chic Regular Fit Apache Neck Viscose Shirt, featuring sleek stripes and silky-smooth fabric for a refined, casual elegance.",
                            Image = "../photos/man/Regular_Fit_Apache_Neck_Viscose_Striped_Short_Sleeve_Shirt_999_EGP.avif",
                            Name = "Regular Fit Apache Neck Viscose Shirt",
                            Price = 999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 1,
                            Description = "Sleek Modern Fit Blazer, expertly tailored for a sharp, contemporary silhouette with premium fabric for lasting sophistication.",
                            Image = "../photos/man/Modern_Fit_Blazer_2999_EGP.avif",
                            Name = "Modern Fit Blazer",
                            Price = 2999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 10,
                            CategoryID = 1,
                            Description = "Luxurious Relax Fit Lined Blazer, combining a laid-back cut with refined lining for unparalleled comfort and style.",
                            Image = "../photos/man/Relax_Fit_Lined_Blazer_3599_EGP.avif",
                            Name = "Relax Fit Lined Blazer",
                            Price = 3599m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 11,
                            CategoryID = 1,
                            Description = "Dapper Checkered Formal Shirt, featuring a crisp check pattern and tailored fit for a polished, professional appearance.",
                            Image = "../photos/man/Checkered_Formal_Shirt_1799_EGP.avif",
                            Name = "Checkered Formal Shirt",
                            Price = 1799m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 12,
                            CategoryID = 1,
                            Description = "Sharp Slim Fit Blazer, designed for a streamlined silhouette with high-quality fabric for a modern, elegant look.",
                            Image = "../photos/man/Slim_Fit_Blazer_2999_EGP.avif",
                            Name = "Slim Fit Blazer",
                            Price = 2999m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 13,
                            CategoryID = 1,
                            Description = "Easygoing Casual Relaxed Fit T-Shirt, crafted from soft, breathable cotton for a comfortable, laid-back everyday style.",
                            Image = "../photos/man/Casual_Relaxed_Fit_T_Shirt_799_EGP.avif",
                            Name = "Casual Relaxed Fit T-Shirt",
                            Price = 799m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 14,
                            CategoryID = 1,
                            Description = "Dynamic Sporty Zip-Up Hoodie, blending cozy warmth with a sleek design for active lifestyles and casual outings.",
                            Image = "../photos/man/Sporty_Zip_Up_Hoodie_1399_EGP.avif",
                            Name = "Sporty Zip-Up Hoodie",
                            Price = 1399m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 15,
                            CategoryID = 1,
                            Description = "Essential Classic Crew Neck T-Shirt, offering timeless simplicity and ultra-soft comfort for versatile, everyday wear.",
                            Image = "../photos/man/Classic_Crew_Neck_T_Shirt_699_EGP.avif",
                            Name = "Classic Crew Neck T-Shirt",
                            Price = 699m,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 16,
                            CategoryID = 1,
                            Description = "Comfort-driven Soft Cotton Casual Shirt, featuring a relaxed fit and buttery-soft fabric for effortless, all-day style.",
                            Image = "../photos/man/Soft_Cotton_Casual_Shirt_1299_EGP.avif",
                            Name = "Soft Cotton Casual Shirt",
                            Price = 1299m,
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("ClothingECommerce.Models.Product", b =>
                {
                    b.HasOne("ClothingECommerce.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ClothingECommerce.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
